### ISSUE TITLE
Docker 手動安裝時出現問題

### ISSUE THREAD

**Issue by erictheng93** [PlayEdu/PlayEdu#22]
全新的Ubuntu 22.04安裝
手動檔 Docker 安裝
$ curl -fsSL https://get.docker.com -o get-docker.sh
$ sudo sh get-docker.sh
--順利通過

第一步、创建 Docker Network --順利通過
第二步、安装 Redis --順利通過
第三步、安装 MinIO --順利通過
第四步、安装 MySQL --順利通過
第五步、安装 PlayEdu 服务 --問題出在這邊

信息如下
Unable to find image 'registry.cn-hangzhou.aliyuncs.com/playedu/light:1.3' locally
1.3: Pulling from playedu/light
44ba2882f8eb: Downloading  5.502MB/30.44MB
2cabec57fa36: Downloading  5.959MB/17.46MB
c4e554d59e12: Downloading  8.935MB/144.8MB
111cbdbeed15: Waiting
ebe3e1fbfc69: Waiting
5f34db4c9a2a: Waiting
4b8b7e31a701: Waiting
0bfaed405e12: Waiting
cf11ac4ba86a: Waiting
ad838c17eb73: Waiting
ff6a626497f8: Waiting
c8942afd8532: Waiting
ce319407183a: Waiting
c1d45d18a5d9: Waiting
191841b4fb1f: Waiting
4f4fb700ef54: Waiting
docker: error pulling image configuration: download failed after attempts=6: EOF.
See 'docker run --help'.
![image](https://github.com/PlayEdu/PlayEdu/assets/70655809/c95a9139-a340-4a47-af26-ea726e9546f0)

請問是什麼原因會產生這個錯誤？
docker: error pulling image configuration: download failed after attempts=6: EOF.
另外，我們可不可以直接用MySQL 8.0來部署？？會出現什麼不可預知的錯誤嗎？？

**Comment by Qsnh** [comment]
不是中国大陆的网络访问我们托管在杭州的镜像仓库估计会有网络问题

**Comment by Qsnh** [comment]
你可以需要挂个大陆的代理pull镜像

**Comment by erictheng93** [comment]
知道了，謝謝。
Docker Compose 安裝測試是沒問題的
