### ISSUE TITLE
对公共对象存储不兼容的情况

### ISSUE THREAD

**Issue by donknap** [PlayEdu/PlayEdu#27]
测试了一下腾讯的cos，阿里云的Oss，还有七牛，发现基本上都不兼容。

### 腾讯的cos

兼容性相对好点，l图片可以正常上传成功，但是在上传视频分片合并时候报错了。

![图片](https://github.com/PlayEdu/PlayEdu/assets/4213382/daa01dc0-7d2e-4bef-9a15-c013da2b964e)

腾讯cos的文件碎片也可以看到数据，个人感觉是腾讯Cos 对分片上传有大小限制要求导致的。

![图片](https://github.com/PlayEdu/PlayEdu/assets/4213382/ee738f5c-b8b5-4881-93ca-3becc1a1e375)

### 七牛

七牛写着支持 s3 协议，但是要求访问时带上 aws 签名。注意：暂不支持通过以上服务域名匿名访问七牛云存储，必须携带 [AWS Signature](https://developer.qiniu.com/kodo/manual/4093/s3-authentication.md)。

图片，视频都可以正常上传，就是缺少签名无法访问。

![图片](https://github.com/PlayEdu/PlayEdu/assets/4213382/706a4896-b65a-4d63-aeac-058589191fa9)

### 阿里云

完全不支持，不支持 http://endpoint/桶名称/对象路径 这种写法。

希望作者可以考虑一下对公有对象存储的支持，只需要简单的改几个小问题。对于用户来说，自建对象存储成本是低，但是公共对象存储使用起来更简单方便。

**Comment by Kiraaaaaaa** [comment]
因为他这个是免费开源的，还有付费的商业版，那个就支持

**Comment by Qsnh** [comment]
目前开源版本的对象存储已经修改为采用 aws s3 的SDK，经过稍微修改就可以支持第三方存储。如有需要请根据最新版本的 playedu 自行修改。
